// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOdSG8R7yY17cA2ANLdUIWs2Bi3ktyZk',
    appId: '1:602586244203:web:43ac1c748e6cd69673bd2e',
    messagingSenderId: '602586244203',
    projectId: 'dartt-voyage',
    authDomain: 'dartt-voyage.firebaseapp.com',
    storageBucket: 'dartt-voyage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM0qBxWep3bLXx92xnlT5Rmf78qgYFVQo',
    appId: '1:602586244203:android:fb0729f9c924941273bd2e',
    messagingSenderId: '602586244203',
    projectId: 'dartt-voyage',
    storageBucket: 'dartt-voyage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkIYFNfjHc3FesfhXHv--2iGlzJUS3Sv4',
    appId: '1:602586244203:ios:b73789d6bf3e138f73bd2e',
    messagingSenderId: '602586244203',
    projectId: 'dartt-voyage',
    storageBucket: 'dartt-voyage.appspot.com',
    iosClientId: '602586244203-p07s7vgfr8vnvg4eo3vliaqq5hta1gfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.darttVoyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkIYFNfjHc3FesfhXHv--2iGlzJUS3Sv4',
    appId: '1:602586244203:ios:b95041b460681d8473bd2e',
    messagingSenderId: '602586244203',
    projectId: 'dartt-voyage',
    storageBucket: 'dartt-voyage.appspot.com',
    iosClientId: '602586244203-eb3ek92jfv1ea3lj88kp8iu9kjaubbtv.apps.googleusercontent.com',
    iosBundleId: 'com.example.darttVoyage.RunnerTests',
  );
}
